# Generated by Django 4.2.7 on 2024-08-09 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_listing_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Listing',
        ),
    ]
