# Generated by Django 4.2.7 on 2024-08-11 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='watchlist',
        ),
    ]
