# Generated by Django 4.2.7 on 2024-08-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_remove_watchlist_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlist',
            name='watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
